name: dask-tutorial
channels:
  - conda-forge
dependencies:
  - python==3.10
  - dask
  - coiled
  - pyarrow
  - ipykernel
  - dask-labextension==6.0
  - jupyterlab
  - datashader
  - s3fs
  - holoviews
  - hvplot
  - python-graphviz
  - pip
  - pip:
    - git+https://github.com/mrocklin/distributed@pydata-nyc-2022
